# 🔴 Task 10: Introduction to NumPy (arrays, basic operations)

In [ ]:
import numpy as np
from scipy.stats import mode

### 1. Create a 1D NumPy array containing the integers from 0 to 9.

In [45]:
arr1 = np.array([0,1,2,3,4,5,6,7,8,9])
print(arr1)


[0 1 2 3 4 5 6 7 8 9]


### 2. Create a 2D NumPy array (3x3) containing random integers between 1 and 20

In [46]:
arr2 = np.random.randint(0, 20, size=(3, 3))
print(arr2)

[[ 0 17  0]
 [10  8  0]
 [ 9 15  0]]


### 3. Create a 3D NumPy array with dimensions (2, 3, 4) filled with ones.

In [48]:
arr3 = np.ones((3, 4, 5))
print(arr3)

[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]


### 4. Add two 1D arrays element-wise.

In [51]:
sum_1d = arr1 + arr1
print(sum_1d)

[ 0  2  4  6  8 10 12 14 16 18]


### 5. Multiply two 2D arrays element-wise.

In [52]:
multiply_2d = arr2 * arr2
print(multiply_2d)

[[  0 289   0]
 [100  64   0]
 [ 81 225   0]]


### 6. Calculate the dot product of two matrices.


In [53]:
mtx3 = np.transpose(mtx2)
dot_prod = np.dot(mtx2, mtx3)
print(dot_prod)

[[113 143 173]
 [143 181 219]
 [173 219 265]]


### 7. Calculate the mean, median, and standard deviation of a 1D array.

In [55]:
mean = np.mean(arr1)
median = np.median(arr1)
mode_result = mode(arr1)
std_dev_1d = np.std(arr1)
print(mean)
print(median)
print(mode_result)
print(std_dev_1d)


4.5
4.5
ModeResult(mode=0, count=1)
2.8722813232690143


### 8. Find the maximum and minimum values in a 2D array.


In [56]:
max = np.max(arr2)
min = np.min(arr2)
print(max, min)

17 0


### 9. Generate an array of 1000 random numbers from a normal distribution with a mean of 0 and a standard deviation of 1.

In [57]:
arr4 = np.random.normal(loc=0, scale=1, size=1000)
print(arr4)

[-2.05545497e-01 -5.59507083e-01 -2.08887888e+00 -8.15590574e-01
 -5.61123014e-01  5.88408706e-02  1.93096379e-01 -1.58278568e-01
 -7.97710176e-01  3.18886454e-01  4.27612740e-01 -3.36552214e-01
  4.57247466e-01  5.85094241e-01  7.25730498e-01 -7.73773930e-01
  4.51460243e-01 -4.05877937e-01 -1.84179369e+00  6.92016932e-01
  1.37732630e+00 -1.24538053e+00 -6.72808288e-01 -5.01547092e-01
 -1.54585797e+00 -2.79251722e+00 -1.01076872e+00  2.03179639e+00
  1.39025359e+00  1.94825808e-01  1.05115055e-01 -5.32779219e-01
 -1.83548150e+00  6.74532966e-01  9.55205410e-01  1.19050760e+00
  3.13191620e-01  2.06828973e+00 -4.26655035e-01 -5.84085164e-01
 -7.40496744e-01 -2.44244661e+00 -9.74768062e-01  1.28129292e+00
  2.30729032e-02 -6.18215534e-01  6.14899691e-01 -2.31429680e-01
 -1.11912627e+00  6.88429735e-01 -1.05645100e+00 -9.95596868e-01
 -2.86362485e-01 -2.09134726e-01  1.50372556e-01 -4.31372309e-01
  6.25202238e-01  5.78599934e-01 -7.09820748e-01 -1.05840381e+00
 -8.12474251e-02 -4.77419

### 10. Create a 2D array of shapes (5, 5) with random integers from a uniform distribution between 10 and 50.

In [58]:
arr5 = np.random.randint(low=10, high=50, size=(5, 5))
print(arr5)

[[45 12 40 16 24]
 [26 49 12 11 22]
 [32 10 30 41 21]
 [45 49 12 29 13]
 [31 47 38 47 47]]


### 11. Calculate the cumulative sum of a 1D array.


In [59]:
cummulative_sum = np.cumsum(arr1)
print(cummulative_sum)

[ 0  1  3  6 10 15 21 28 36 45]


### 12. Compute the correlation coefficient matrix of a 2D array.


In [61]:
corr_coef_arr = np.corrcoef(arr2)
print(corr_coef_arr)

[[1.         0.32732684 0.80295507]
 [0.32732684 1.         0.82603319]
 [0.80295507 0.82603319 1.        ]]


### 13. Simulate rolling a six-sided die 1000 times and count the frequency of each outcome.


In [62]:
diceroll = np.random.randint(low=0, high=7, size=1000)
outcome_counts = np.bincount(diceroll, minlength=6)
print(diceroll)
print("Outcome\tFrequency")
for i in range(1, 7):
    print(f"{i}\t{outcome_counts[i-1]}")

[2 2 6 5 4 2 5 3 5 3 5 0 6 4 4 0 1 4 6 3 5 0 3 2 2 0 1 4 4 3 6 3 3 4 6 3 6
 4 3 2 4 1 2 5 5 4 0 1 0 5 4 3 6 4 1 0 6 0 6 1 2 6 5 5 0 5 6 1 4 6 1 1 3 5
 4 2 5 5 5 6 1 4 1 3 2 2 1 4 6 5 6 2 1 6 6 0 3 5 1 4 6 5 6 3 0 3 0 2 3 0 1
 2 6 0 6 1 2 0 6 1 1 6 3 3 1 1 1 5 0 6 6 5 0 3 0 0 5 3 1 6 1 4 0 4 4 2 1 2
 4 1 2 0 6 4 6 3 3 3 2 2 0 5 2 3 3 4 1 6 6 4 5 6 5 5 0 0 4 1 5 2 5 1 3 3 0
 0 0 4 5 4 6 6 4 2 5 5 4 5 4 3 6 2 4 3 3 6 6 0 5 3 5 5 4 0 6 5 4 1 6 0 3 0
 0 5 6 5 2 5 2 5 2 0 5 0 3 4 3 6 3 3 6 5 6 2 6 6 6 5 4 0 1 5 3 5 6 4 6 5 5
 3 0 4 4 6 4 6 0 6 5 3 5 6 3 3 1 5 0 3 1 0 3 5 6 0 1 6 2 5 4 0 1 2 2 4 6 5
 2 1 1 6 5 1 2 1 2 1 0 6 6 3 6 5 6 5 0 3 6 3 2 2 3 5 1 2 4 3 6 3 1 2 0 1 4
 6 3 1 5 6 5 1 0 5 4 2 1 3 2 1 3 2 2 5 6 2 5 1 3 5 0 5 0 2 5 6 0 1 1 2 2 5
 0 5 6 5 0 1 3 6 3 0 3 4 1 0 6 6 6 4 4 4 1 0 4 3 1 1 0 5 2 2 1 5 6 4 0 1 6
 6 2 6 5 2 2 2 4 4 1 1 1 6 3 2 3 1 1 1 6 5 0 0 4 1 2 5 6 2 6 2 2 1 3 0 3 0
 1 0 1 1 4 1 0 1 0 2 5 5 5 0 5 0 2 6 5 4 5 2 5 3 3 0 3 3 2 3 6 3 2 2 3 2 3
 0 2 4 1 1 4 4 4 3 5 5 2 