# 🔴 Task 21-> Linear algebra and calculus in NumPy

In [118]:
import numpy as np
from scipy.linalg import lu
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

## 1. Matrix Creation and Manipulation

In [119]:
zero_matrix = np.zeros((5, 5))
print("Zero matrix:")
print(zero_matrix)

Zero matrix:
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [120]:
identity_matrix = np.eye(5)
print("Identity matrix:")
print(identity_matrix)
print()

Identity matrix:
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]



In [121]:
random_matrix = np.random.rand(5, 5)
print("Random matrix:")
print(random_matrix)
print()

Random matrix:
[[0.27101034 0.44369582 0.19859305 0.65799473 0.86982656]
 [0.47217351 0.7835475  0.599717   0.15794412 0.36680106]
 [0.20086946 0.02288165 0.187835   0.50583173 0.94116777]
 [0.10994497 0.83433685 0.8633589  0.700531   0.49968349]
 [0.65705018 0.06125752 0.65377724 0.38131713 0.08628182]]



### 🟡 Addition

In [122]:
addition = zero_matrix + identity_matrix
print(addition)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


### 🟢 Subtraction

In [123]:
subtraction = identity_matrix - random_matrix
print(subtraction)

[[ 0.72898966 -0.44369582 -0.19859305 -0.65799473 -0.86982656]
 [-0.47217351  0.2164525  -0.599717   -0.15794412 -0.36680106]
 [-0.20086946 -0.02288165  0.812165   -0.50583173 -0.94116777]
 [-0.10994497 -0.83433685 -0.8633589   0.299469   -0.49968349]
 [-0.65705018 -0.06125752 -0.65377724 -0.38131713  0.91371818]]


### ⚫ Multiplication

In [124]:
multiplication = identity_matrix * zero_matrix
print(multiplication)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


## 2. Solving Linear Equations


#### x + 6y - 9z = 8
#### -4x + 2y + z = 3
#### -7x - 3y + 8z = 9

In [125]:
coefficient_mat = np.array([[1, 6, -9],
              [-4, 2, 1],
              [-7, -3, 8]])
is_equal = np.array([8, 3, 9])

linear_solve = np.linalg.solve(coefficient_mat, is_equal)

In [126]:
print("Solution to the system of linear equations:")
print("x =", linear_solve[0])
print("y =", linear_solve[1])
print("z =", linear_solve[2])

Solution to the system of linear equations:
x = -4.692307692307689
y = -5.38461538461538
z = -4.999999999999996


#### 🟤 LU Decomposition

In [127]:
P, L, U = lu(coefficient_mat)
print("P:")
print(P)
print()
print("L:")
print(L)
print()
print("U:")
print(U)
print()

P:
[[0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]]

L:
[[ 1.          0.          0.        ]
 [-0.14285714  1.          0.        ]
 [ 0.57142857  0.66666667  1.        ]]

U:
[[-7.         -3.          8.        ]
 [ 0.          5.57142857 -7.85714286]
 [ 0.          0.          1.66666667]]



#### 🔴 QR Decomposition

In [128]:
Q, R = np.linalg.qr(coefficient_mat)
print("Q:")
print(Q)
print()
print("R:")
print(R)

Q:
[[-0.12309149 -0.86576808  0.48507125]
 [ 0.49236596 -0.47766515 -0.72760688]
 [ 0.86164044  0.14927036  0.48507125]]

R:
[[-8.1240384  -2.33873833  8.49331288]
 [ 0.         -6.59774985  8.50841043]
 [ 0.          0.         -1.21267813]]


## 3. Eigenvalues and Eigenvectors

In [129]:
eigenval, eigenvec = np.linalg.eig(coefficient_mat)

In [130]:
print("Eigen Value:")
print(eigenval)
print()
print("Eigen Vector:")
print(eigenvec)

Eigen Value:
[11.37678579 -2.58607524  2.20928945]

Eigen Vector:
[[-0.5167845   0.67388003 -0.09228359]
 [ 0.30573385  0.46204645 -0.83417822]
 [ 0.7996628   0.57654035 -0.54371908]]


In [131]:
recon = np.dot(eigenvec, np.diag(eigenval)).dot(np.linalg.inv(eigenvec))
print("Reconstructed:")
print(recon)

Reconstructed:
[[ 1.  6. -9.]
 [-4.  2.  1.]
 [-7. -3.  8.]]


In [132]:
if np.allclose(recon, coefficient_mat):
    print("Both are Same")
else:
    print("Not Same")

Both are Same


## 4. Vector Operations

In [133]:
v1 = np.array([7, 3, 1])
v2 = np.array([8, 2, 6])
print(v1, v2)

[7 3 1] [8 2 6]


### 🟡 Addition

In [134]:
addition = v1 +v2
print(addition)

[15  5  7]


### 🟢 Subtraction

In [135]:
subtraction = v2 - v1
print(subtraction)

[ 1 -1  5]


### ⚫ Multiplication

In [136]:
multiplication = v1 * v2
print(multiplication)

[56  6  6]


### 🔘 Dot Product

In [137]:
dot_prod = np.dot(v1, v2)
print(dot_prod)

68


### ⭕ Cross Product

In [138]:
cross_prod = np.cross(v1, v2)
print(cross_prod)

[ 16 -34 -10]


### 🌑Vector normalization


In [139]:
v1_normal = v1 / np.linalg.norm(v1)
v2_normal = v2 / np.linalg.norm(v2)
print("Normalized Vectors:")
print("Vector 1:")
print(v1_normal)
print("Vector 2:")
print(v2_normal)

Normalized Vectors:
Vector 1:
[0.91132238 0.39056673 0.13018891]
Vector 2:
[0.78446454 0.19611614 0.58834841]


## 5. Matrix Decomposition

In [140]:
iris_df = pd.read_csv("Iris.csv")

In [142]:
le = LabelEncoder()
iris_df['species'] = le.fit_transform(iris_df['Species'])

scl = StandardScaler()
iris_df_scl = scl.fit_transform(iris_df.drop('Species', axis=1))

### PCA using SVD:

In [149]:
U, s, Vh = np.linalg.svd(iris_df_scl, full_matrices=False)
X_reconst = np.dot(U, np.diag(s)).dot(Vh)

In [150]:
print("Original data shape:", iris_df.shape)
print("Scaled data shape:", iris_df_scl.shape)
print("U shape:", U.shape)
print("Singular values (s):", s)
print("Vh shape:", Vh.shape)
print("Reconstructed data shape:", X_reconst.shape)


Original data shape: (150, 7)
Scaled data shape: (150, 6)
U shape: (150, 6)
Singular values (s): [26.50252364 11.75896291  6.18291866  3.6613837   2.16811868  1.73438162]
Vh shape: (6, 6)
Reconstructed data shape: (150, 6)
