# 🔴 Task 11: NumPy advanced operations (indexing, slicing, broadcasting)

In [ ]:
import numpy as np

### 1. Given a 2D array of shape (5, 5), extract a 3x3 sub-array starting from the element at position (1, 1).


In [9]:
arr2 = np.random.randint(0, 20, size=(5, 5))
print("Original Matrix")
print(arr2)
print()
sub_arr = arr2[1:4, 1:4]
print("Sub-Matrix")
print(sub_arr)

Original Matrix
[[ 9  4 16  7  8]
 [ 9 10 15  4  6]
 [ 9  9  1  7 18]
 [ 6 15 19  5 17]
 [11 18 17  8 18]]

Sub-Matrix
[[10 15  4]
 [ 9  1  7]
 [15 19  5]]


### 2. From a 3D array of shape (4, 3, 2), extract all elements in the first two rows and all columns of the second slice along the third axis.

In [20]:
arr2 = np.random.randint(1, 11, size=(4,3,2))
print("Original Array")
print(arr2)
print()
sub_arr = arr2[:2, 1, :]
print("Sub_Array")
print(sub_arr)

Original Array
[[[ 7  7]
  [ 7 10]
  [ 1  1]]

 [[ 1  9]
  [10  2]
  [ 8  2]]

 [[ 1  1]
  [ 4  7]
  [10  5]]

 [[ 5  2]
  [ 5  5]
  [ 2  9]]]

Sub_Array
[[ 7 10]
 [10  2]]


### 3. Given an array of integers, use fancy indexing to extract elements at positions [1, 3, 4, 7].

In [36]:
arr3 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("Original Array")
print(arr3)
new_arr = arr3[[0, 1, 2], [1, 2, 0]]

print("Fancy Array")
print(new_arr)

Original Array
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Fancy Array
[2 6 7]


### 4. Given a 2D array, use fancy indexing to select rows [0, 2, 3] and columns [1, 3].

In [42]:
arr4 = np.array([[1, 2, 3, 4], 
                 [5, 6, 7, 8],
                 [9, 10, 11, 12],
                 [13, 14, 15, 16]])

row_indices = np.array([0, 2, 3])
col_indices = np.array([1, 3])

arr5 = arr4[row_indices[:, None], col_indices]

print("Original Array:")
print(arr4)
print()
print("Fancy Array:")
print(arr5)

Original Array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

Fancy Array:
[[ 2  4]
 [10 12]
 [14 16]]


### 5. From a 1D array of random integers, extract all elements that are greater than 10.

In [44]:
arr6 = np.random.randint(1, 21, size=21)
arr7 = arr6[arr6 > 10]

print("Original Matrix")
print(arr6)
print()
print("Greater than 10")
print(arr7)

Original Matrix
[18 13  9 16  8  4  1 10  8 10 12  8 20  7 19  8  5  6  1 15 12]

Greater than 10
[18 13 16 12 20 19 15 12]


### 6. Given a 2D array of shape (5, 5), replace all elements greater than 15 with the value 0

In [53]:
 arr8 = np.random.randint(1,21,size=(5,5))
print("Original Matrix")
print(arr8)
print()

arr8[arr8 > 15] = 0
print("Replaced Values > 15 with 0")
print(arr8)

Original Matrix
[[ 3 16  6  6  5]
 [ 6  8 19 14  7]
 [ 6  4 13 20 14]
 [11  6  2  8  4]
 [ 8 19 10 11 16]]

Replaced Values > 15 with 0
[[ 3  0  6  6  5]
 [ 6  8  0 14  7]
 [ 6  4 13  0 14]
 [11  6  2  8  4]
 [ 8  0 10 11  0]]


# Broadcasting

#### 1. Add a 1D array of shape (3,) to each row of a 2D array of shape (4, 3)

In [2]:
import numpy as np
arr9 = np.array([[10, 2, 3], 
                   [7, 9, 6],
                   [4, 2, 9],
                   [1, 4, 2]])

arr10 = np.array([120, 400, 780])

result = arr9 + arr10

print(result)

[[130 402 783]
 [127 409 786]
 [124 402 789]
 [121 404 782]]


#### 2. Multiply a 2D array of shape (3, 3) by a 1D array of shape (3,).

In [3]:
arr11 = np.array([[2, 4, 6], 
                   [7, 6, 1], 
                   [8, 5, 6]])

arr12 = np.array([10, 20, 30])

result = arr11 @ arr12

print(result)

[280 220 360]


#### 3. Create two 2D arrays of shapes (3, 1) and (1, 4) respectively, and perform element-wise addition.

In [4]:
arr13 = np.array([[2], 
                  [7],
                  [9]])

arr14 = np.array([[15, 37, 22, 56]])

result = arr13 + arr14

print(result)

[[17 39 24 58]
 [22 44 29 63]
 [24 46 31 65]]


#### 4. Given a 3D array of shape (2, 3, 4), add a 2D array of shape (3, 4) to each 2D slice along the first axis.

In [5]:
arr15 = np.array([[[ 1,  2,  3,  4],
                    [ 5,  6,  7,  8],
                    [ 9, 10, 11, 12]],
                   [[13, 14, 15, 16],
                    [17, 18, 19, 20],
                    [21, 22, 23, 24]]])

arr16 = np.array([[100, 200, 300, 400],
                   [500, 600, 700, 800],
                   [900, 1000, 1100, 1200]])

result = arr15 + arr16[None, :, :]

print(result)

[[[ 101  202  303  404]
  [ 505  606  707  808]
  [ 909 1010 1111 1212]]

 [[ 113  214  315  416]
  [ 517  618  719  820]
  [ 921 1022 1123 1224]]]


#### 5. Given a 2D array, use slicing to extract every second row and every second column, then add a 1D array to each row of the sliced array:

In [11]:
arr17 = np.array([[8, 2, 3, 9],
                  [3, 6, 3, 8],
                  [8, 1, 19, 15],
                  [15, 18, 11, 18]])

sl_arr = arr17[::2, ::2]

arr18 = np.array([100, 200])

result = sl_arr + arr18.reshape(1, -1)

print(result)

[[108 203]
 [108 219]]


#### 6. From a 3D array of shape (4, 3, 2), extract a sub-array using slicing and then use broadcasting to subtract a 2D array from each slice along the third axis.

In [19]:
sub_arr = np.array([[[5, 10],
                    [15, 20],
                    [25, 30]],
                   [[35, 40],
                    [45, 50],
                    [55, 60]],
                   [[65, 70],
                    [75, 80],
                    [85, 90]],
                   [[95, 100],
                    [105, 110],
                    [115, 120]]])

arr19 = np.array([[5, 10],
                   [15, 20]])

sub_arr2 = sub_arr[::2, ::2, :]

result = sub_arr2 - arr19[:, None, :]

print(result)

[[[ 0  0]
  [20 20]]

 [[50 50]
  [70 70]]]


#### 7. Given a 2D array, extract the diagonal elements and create a 1D array.

In [20]:
arr20 = np.array([[5, 10, 15],
                   [20, 25, 30],
                   [35, 40, 45]])

diag_arr = arr20.diagonal()

print(diag_arr)

[ 5 25 45]


#### 8. Use slicing to reverse the order of elements in each row of a 2D array.

In [21]:
arr21 = np.array([[5, 10, 15],
                   [20, 25, 30],
                   [35, 40, 45]])

rev_arr = arr21[:, ::-1]

print(rev_arr)

[[15 10  5]
 [30 25 20]
 [45 40 35]]


#### 9. Given a 3D array of shape (4, 5, 6), use slicing to extract a sub-array of shape (2, 3, 4) and then use broadcasting to add a 1D array of shape (4,) to each row along the third axis.

In [23]:
arr22 = np.random.rand(4, 5, 6)

sub_arr = arr22[:2, :3, :4]

arr23 = np.array([1, 2, 3, 4])

result = sub_arr + arr23[None, None, :]

print(result)

[[[1.0645715  2.53392413 3.3958336  4.65409868]
  [1.93249583 2.82394003 3.80069559 4.20214583]
  [1.68750082 2.18130959 3.71677674 4.29554714]]

 [[1.07965851 2.13708401 3.407733   4.12751778]
  [1.74110112 2.5477271  3.95194547 4.07667103]
  [1.20521389 2.24947436 3.00093942 4.99081325]]]


#### 10. Create a 2D array and use both slicing and broadcasting to set the last column to the sum of the first two columns for each row.

In [24]:
arr24 = np.array([[5, 10, 15],
                   [20, 25, 30],
                   [35, 40, 45]])

arr24[:, -1] = arr24[:, 0] + arr24[:, 1]

print(arr24)

[[ 5 10 15]
 [20 25 45]
 [35 40 75]]
